"""Pair each real image with simulated sensor readings.

Read this before trusting any fusion result.
=============================================

No public dataset pairs photographs of spoiling food with synchronised gas,
temperature, humidity and weight measurements. Building one needs a physical
rig running for months. This module therefore constructs the paired corpus by
simulation: the images are real and their fresh/rotten labels are real, but
every numeric sensor feature is generated by the physical model in
:mod:`freshkeeper.hardware.spoilage_model`.

Consequently the fusion accuracies reported in the thesis measure whether the
architecture can exploit sensor information *under the stated physical model*.
They are not, and must not be quoted as, a measurement of how the system would
perform on a real shelf. Validating against instrumented hardware is the first
item of future work.

How the pairing works
---------------------

Each item gets a storage trajectory: a commodity, a fridge with its own
setpoint and door-opening habits, and a random age. Integrating the physics
over that trajectory gives a spoilage extent in [0, 1], which yields both the
three-class target and the sensor features.

The image is then chosen to match how the item would *look* at that extent,
and this is where the interesting part is. Visible change lags physical
change. An item that is microbiologically well advanced can still photograph
as sound, which is the entire reason for putting gas sensors in the box.
The model encodes that lag with a per-commodity visual threshold: below it the
item is drawn from the fresh image pool, above it from the rotten pool.

The consequence is deliberate. Items in the "marginal" band straddle the
visual threshold, so marginal items draw images from both pools. Appearance
alone therefore cannot separate marginal from fresh, and a vision-only model
has an accuracy ceiling well below 100% by construction. Whether the sensor
channel recovers that gap is exactly what the ablation in
:mod:`freshkeeper.ml.evaluate` tests.
"""

from __future__ import annotations

import csv
import json
import random
import sys
from collections import Counter, defaultdict
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from freshkeeper.hardware.sim_backend import (  # noqa: E402
    AMBIENT_AMMONIA_PPM, AMBIENT_ETHANOL_PPM, FridgeThermalModel,
    MQ3_ETHANOL_A, MQ3_ETHANOL_B, MQ135_AMMONIA_A, MQ135_AMMONIA_B,
)
from freshkeeper.hardware.spoilage_model import (  # noqa: E402
    FOOD_PROFILES, MARGINAL_THRESHOLD, SPOILED_THRESHOLD,
    extent_to_label, integrate_spoilage, mq_ppm_from_ratio, mq_ratio_from_ppm,
    profile_for,
)
from freshkeeper.ml.model import CLASS_NAMES  # noqa: E402

MANIFEST = ROOT / "data" / "processed" / "manifest_grouped.csv"
EMB_DIR = ROOT / "data" / "embeddings"
OUT_DIR = ROOT / "data" / "sensor_corpus"
RESULTS = ROOT / "results"
SEED = 20260908

#: Spoilage extent at which an item starts to *look* spoiled. Set above
#: MARGINAL_THRESHOLD so that the marginal band straddles it: some marginal
#: items still photograph as fresh. Firm-skinned commodities hide spoilage for
#: longer, which is why the value varies by commodity.
VISUAL_THRESHOLD = {
    "strawberry": 0.50, "banana": 0.52, "grape": 0.54, "guava": 0.56,
    "jujube": 0.58, "orange": 0.60, "apple": 0.62, "pomegranate": 0.64,
}
DEFAULT_VISUAL_THRESHOLD = 0.55

#: Fridges differ. Some run at 2 degC and are barely opened; some sit at 8 degC
#: in a shared flat and are opened forty times a day. Sampling over that range
#: is what stops the model learning a single storage regime.
FRIDGE_POPULATION = [
    # (setpoint_c, openings_per_day, weight)
    (2.5, 6.0, 0.20),
    (4.0, 10.0, 0.40),
    (5.5, 16.0, 0.25),
    (7.5, 24.0, 0.15),
]

MEASUREMENT_INTERVAL_HOURS = 0.5


def sample_fridge(rng: random.Random) -> FridgeThermalModel:
    weights = [w for *_, w in FRIDGE_POPULATION]
    setpoint, openings, _ = rng.choices(FRIDGE_POPULATION, weights=weights)[0]
    return FridgeThermalModel(
        setpoint_c=setpoint + rng.gauss(0.0, 0.4),
        openings_per_day=max(1.0, openings + rng.gauss(0.0, 2.0)),
        base_humidity=min(0.95, max(0.60, rng.gauss(0.85, 0.05))),
    )


def quantise(ppm: float, coeff_a: float, coeff_b: float, ambient: float,
             elapsed_hours: float, rng: random.Random) -> float:
    """Same analogue chain as the simulated backend, for consistency."""
    ratio = mq_ratio_from_ppm(ppm + ambient, coeff_a, coeff_b)
    drift = 1.0 + 0.004 * (elapsed_hours / 24.0)
    ratio *= drift
    vout = 3.3 / (1.0 + ratio) + rng.gauss(0.0, 0.004)
    code = min(1023, max(1, int(round(vout / 3.3 * 1023))))
    vout_q = code / 1023 * 3.3
    recovered = max(1e-6, (3.3 / vout_q) - 1.0) / drift
    return round(mq_ppm_from_ratio(recovered, coeff_a, coeff_b), 3)


def build(rows: list[dict], rng: random.Random) -> tuple[np.ndarray, np.ndarray, list[int]]:
    """Generate one sensor sample and a target class for every image.

    Returns the feature matrix, the class targets, and the index into ``rows``
    of the image chosen for each sample.
    """
    # Pool image indices by (commodity, fresh/rotten) so a sample can draw an
    # image that matches how the item would look.
    pools: dict[tuple[str, int], list[int]] = defaultdict(list)
    for i, row in enumerate(rows):
        pools[(row["fruit_type"], int(row["label"]))].append(i)

    features: list[list[float]] = []
    targets: list[int] = []
    image_idx: list[int] = []

    commodities = sorted(FOOD_PROFILES)
    n_samples = len(rows)

    for _ in range(n_samples):
        commodity = rng.choice(commodities)
        profile = profile_for(commodity)
        fridge = sample_fridge(rng)

        initial_mass = profile.typical_mass_g * rng.uniform(0.80, 1.20)

        # Sample the target spoilage extent uniformly, then solve for the age
        # that produces it, rather than sampling age uniformly. Extent is a
        # sigmoid in time, so uniform ages pile up in the saturated tail: the
        # first version of this produced 69% spoiled samples and starved the
        # fresh and marginal classes. Sampling in extent space covers the
        # decision boundaries evenly, which is where the classes are decided.
        target_extent = rng.uniform(0.02, 0.98)
        probe = _age_for_extent(
            profile, fridge, initial_mass, target_extent,
            _nominal_shelf_life_days(commodity), rng)
        if probe is None:
            continue
        state, age_hours, final_temp_c, final_rh = probe

        ethanol = quantise(state.ethanol_ppm, MQ3_ETHANOL_A, MQ3_ETHANOL_B,
                           AMBIENT_ETHANOL_PPM, age_hours, rng)
        ammonia = quantise(state.ammonia_ppm, MQ135_AMMONIA_A, MQ135_AMMONIA_B,
                           AMBIENT_AMMONIA_PPM, age_hours, rng)
        temperature = round(final_temp_c + rng.gauss(0.0, 0.25), 1)
        rh = round(min(100.0, max(0.0, final_rh * 100 + rng.gauss(0.0, 1.0))), 1)
        mass_delta = round(state.mass_g - initial_mass + rng.gauss(0.0, 0.4), 1)

        features.append([ethanol, ammonia, temperature, rh, mass_delta])
        targets.append(CLASS_NAMES.index(extent_to_label(state.spoilage_extent)))

        # Choose an image consistent with how the item looks at this extent.
        threshold = VISUAL_THRESHOLD.get(commodity, DEFAULT_VISUAL_THRESHOLD)
        looks_rotten = int(state.spoilage_extent >= threshold)
        pool = pools.get((commodity, looks_rotten)) or pools.get((commodity, 1 - looks_rotten))
        image_idx.append(rng.choice(pool))

    return np.array(features, dtype=np.float32), np.array(targets, dtype=np.int32), image_idx


def _age_for_extent(profile, fridge, initial_mass, target_extent,
                    shelf_life_days, rng):
    """Find the storage age at which an item reaches ``target_extent``.

    Integrate the trajectory once over a generous window and scan for the first
    step at or past the target. Spoilage extent is monotonic in time under this
    model, so one pass finds the crossing exactly; the bisection this replaced
    re-integrated from zero on every probe and was roughly a hundred times
    slower for no extra accuracy.

    Returns ``(state, age_hours, temperature_c, relative_humidity)``, or the
    final state if the target is never reached inside the window.
    """
    horizon = 3.0 * 24 * shelf_life_days
    temps, humidity = fridge.series(horizon, MEASUREMENT_INTERVAL_HOURS, rng)
    if not temps:
        return None
    states = integrate_spoilage(
        profile, temps, humidity, MEASUREMENT_INTERVAL_HOURS, initial_mass)

    for i, state in enumerate(states):
        if state.spoilage_extent >= target_extent:
            return state, state.elapsed_hours, temps[i], humidity[i]

    last = len(states) - 1
    return states[last], states[last].elapsed_hours, temps[last], humidity[last]


def _nominal_shelf_life_days(commodity: str) -> float:
    from freshkeeper.hardware.spoilage_model import PUBLISHED_SHELF_LIFE_DAYS
    return PUBLISHED_SHELF_LIFE_DAYS.get(commodity, 14.0)


def main() -> int:
    with MANIFEST.open() as fh:
        rows = list(csv.DictReader(fh))
    corpus = np.load(EMB_DIR / "corpus_x.npy")
    assert len(corpus) == len(rows), "embedding cache and manifest disagree"

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    RESULTS.mkdir(exist_ok=True)
    summary = {}

    for split in ("train", "val", "test"):
        subset_idx = [i for i, r in enumerate(rows) if r["split"] == split]
        subset = [rows[i] for i in subset_idx]
        # Seed per split so regenerating one split does not disturb the others.
        rng = random.Random(SEED + hash(split) % 10_000)
        feats, targets, local_img = build(subset, rng)
        embeddings = corpus[[subset_idx[i] for i in local_img]]

        np.save(OUT_DIR / f"{split}_sensor.npy", feats)
        np.save(OUT_DIR / f"{split}_embedding.npy", embeddings.astype(np.float32))
        np.save(OUT_DIR / f"{split}_y.npy", targets)

        dist = Counter(targets)
        summary[split] = {
            "n": int(len(targets)),
            "class_counts": {CLASS_NAMES[k]: int(v) for k, v in sorted(dist.items())},
        }
        print(f"  {split:5s} n={len(targets):5d}  " + "  ".join(
            f"{CLASS_NAMES[k]}={dist[k]}" for k in range(len(CLASS_NAMES))))

    meta = {
        "seed": SEED,
        "measurement_interval_hours": MEASUREMENT_INTERVAL_HOURS,
        "marginal_threshold": MARGINAL_THRESHOLD,
        "spoiled_threshold": SPOILED_THRESHOLD,
        "visual_thresholds": VISUAL_THRESHOLD,
        "fridge_population": [
            {"setpoint_c": s, "openings_per_day": o, "weight": w}
            for s, o, w in FRIDGE_POPULATION
        ],
        "splits": summary,
        "provenance": (
            "Images and fresh/rotten labels are real "
            "(Project-AgML/fresh_rotten_fruit_classification, CC-BY-4.0). "
            "All numeric sensor features are simulated from the physical model "
            "in freshkeeper.hardware.spoilage_model and have not been validated "
            "against instrumented hardware."
        ),
    }
    with (RESULTS / "sensor_corpus_meta.json").open("w") as fh:
        json.dump(meta, fh, indent=2)
    print(f"\nWrote {OUT_DIR} and {RESULTS / 'sensor_corpus_meta.json'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
