"""Chapter 5: Results and Discussion."""

from docx_builder import (
    bullet, code_block, figure, heading, numbered, para, reset_numbering,
    rich_para, table,
)

from results import Results

FIG = "../freshkeeper/docs/figures"


def build(document) -> None:
    R = Results()
    heading(document, "Results and Discussion", 1)

    para(document,
         "Everything reported here was produced by running the pipeline "
         "described in Chapter 4. Each subsection states what was measured and "
         "then what it supports, because for two of these results those are "
         "different things.")

    rich_para(document, [
        ("A reminder before the numbers. ", "b"),
        ("The images and their fresh/rotten labels are real. All gas, "
         "temperature, humidity and mass features are generated by the physical "
         "model. The Raspberry Pi drivers are written but unvalidated. Results "
         "in section 5.2 rest on real data; results in 5.3 rest on the "
         "simulation and are bounded accordingly.", ""),
    ])

    # ==================================================================
    heading(document, "Validation of the physical model", 2)

    para(document,
         "The model has to be right before anything built on it means anything, "
         "so it is checked first, against the published shelf lives its "
         "coefficients were fitted to.")

    _max_err = max(abs(r["error_percent"]) for r in R.shelf["rows"])
    table(document,
          ["Commodity", "Published (days)", "Model (days)", "Error"],
          [[r["commodity"], f"{r['published_days']:.1f}", f"{r['modelled_days']:.1f}",
            f"{r['error_percent']:+.1f}%"] for r in R.shelf["rows"]],
          "Table 6",
          "Modelled versus published shelf life at 4 °C and 85% relative "
          f"humidity. Agreement is within {_max_err:.1f}% across a range "
          "spanning an order of magnitude, from five days to sixty.",
          widths=[4.5, 3.5, 3.5, 3.0])

    para(document,
         "This is a weaker result than it looks, and saying so is more useful "
         "than claiming otherwise: the coefficients were solved backwards from "
         "these values, so close agreement mainly confirms the solver worked. "
         "The genuine test is whether the model behaves correctly where it was "
         "not fitted.")

    figure(document, f"{FIG}/shelf_life_validation.png", "Figure 10",
           "Left: modelled against published shelf lives. Right: temperature "
           "dependence, which was not fitted. The near-linear relationship on a "
           "logarithmic axis is what the Ratkowsky model implies, and the "
           "commodity ordering is preserved across the whole range.",
           width_cm=15.5)

    para(document,
         "The right-hand panel is the informative one. Storage temperature was "
         "never used in calibration — every coefficient was fitted at 4 °C — yet "
         "the temperature response falls out with the right shape and "
         f"magnitude. Strawberries last {R.shelf['temperature_sweep_days']['strawberry']['2.0']:.1f} "
         f"days at 2 °C and {R.shelf['temperature_sweep_days']['strawberry']['15.0']:.1f} days at "
         "15 °C. The implied temperature coefficient across a ten-degree "
         "interval is roughly "
         f"{(R.shelf['temperature_sweep_days']['strawberry']['4.0'] / R.shelf['temperature_sweep_days']['strawberry']['15.0']) ** (10 / 11):.0f}, "
         "which sits inside the 2 to 4 range reported for microbial "
         "spoilage. The model was not tuned to produce that.")

    para(document,
         "Path dependence works as intended. Two identical strawberries aged for "
         "the same total time reach different states when one spends three days "
         "at 14 °C, and the difference is what the Ratkowsky integral predicts. "
         "This is the property that distinguishes measuring conditions from "
         "trusting a printed date, and it is the strongest argument the physical "
         "model supplies for the system as a whole.")

    rich_para(document, [
        ("RQ1 is answered affirmatively. ", "b"),
        ("A model assembled from the Ratkowsky and Gompertz equations "
         f"reproduces published refrigerated shelf lives to within {_max_err:.1f}% across "
         "eight commodities, and extrapolates to temperatures it was not fitted "
         "at with a biologically plausible coefficient.", ""),
    ])

    # ==================================================================
    heading(document, "Visual classification", 2)

    para(document,
         "The binary fresh-versus-rotten classifier is the one result in this "
         "thesis measured entirely on real data.")

    table(document,
          ["Metric", "Value"],
          [["Test accuracy", R.f4(R.visual["accuracy"])],
           ["ROC AUC", R.f4(R.visual["auc"])],
           ["Macro F1", R.f4(R.visual["macro_f1"])],
           ["Recall, rotten class", R.f4(R.visual["rotten_recall"])],
           ["Precision, rotten class", R.f4(R.visual["rotten_precision"])],
           ["Test images", R.n(R.visual["n"])]],
          "Table 7",
          "Visual CNN on the held-out, group-aware test split. MobileNetV2 with "
          f"two-stage transfer learning: {R.stage1_epochs} epochs of head training "
          f"on cached embeddings, then {R.stage2_epochs} epochs fine-tuning the top "
          "40 backbone layers.",
          widths=[7.0, 4.0])

    figure(document, f"{FIG}/confusion_visual_cnn.png", "Figure 11",
           "Confusion matrix for binary classification. Errors are close to "
           f"symmetric: {R.visual['confusion_matrix'][0][1]} fresh items called "
           f"rotten, {R.visual['confusion_matrix'][1][0]} rotten called fresh.",
           width_cm=9.5)

    para(document,
         f"{R.pct(R.visual['accuracy'])} accuracy with an AUC of "
         f"{R.f4(R.visual['auc'])} is a strong number, and it would "
         "be easy to present it as the headline finding. It should not be.")

    para(document,
         "Breaking the result down by commodity shows where the difficulty sits.")

    _pc = sorted(R.per_commodity, key=lambda r: -r["accuracy"])
    table(document,
          ["Commodity", "Test images", "Accuracy", "AUC"],
          [[r["commodity"].capitalize(), str(r["n"]), R.f4(r["accuracy"]), R.f4(r["auc"])]
           for r in _pc]
          + [["**Overall**", f"**{R.n(R.visual['n'])}**",
              f"**{R.f4(R.visual['accuracy'])}**", f"**{R.f4(R.visual['auc'])}**"]],
          "Table 8",
          f"Per-commodity binary classification. {_pc[0]['commodity'].capitalize()} is "
          f"classified best; {_pc[-1]['commodity']} is hardest.",
          widths=[4.0, 3.4, 3.4, 3.2])

    para(document,
         "Bananas and guavas are separated almost perfectly, which is "
         "unsurprising: a rotten banana is black and a fresh one is yellow, and "
         "no classifier needs subtlety for that. Oranges are hardest at "
         f"{R.pct(next(r['accuracy'] for r in _pc if r['commodity'] == 'orange'))}, and the "
         "plausible reason is that citrus spoilage begins as localised mould on "
         "a rind whose colour barely changes, so the global appearance of a "
         "spoiling orange stays closer to a sound one.")

    para(document,
         "The pattern is informative. Difficulty tracks how much of the fruit's "
         "appearance changes, not how far spoilage has progressed. That is "
         "another way of saying the classifier is measuring visible change, "
         "which is exactly the limitation the next subsection develops.")

    heading(document, "Why this figure demonstrates less than it appears", 3)

    para(document,
         "The first run of this model, on the naive split, scored "
         f"{R.pct(R.naive_best_val) if R.naive_best_val else 'about 99.7%'} on "
         "validation, which prompted the audit described in Chapter 4. That "
         f"audit found genuine near-duplicate leakage — {R.pct(R.naive_leak)} "
         "of test images within cosine 0.95 of a training image — and "
         "eliminating it produced a split with "
         f"{R.pct(R.audit['residual_test_leakage_fraction'], 2)} residual "
         f"leakage. The retrained model then scored {R.pct(R.stage2_best_val)}.")

    para(document,
         "Leakage was not the explanation. The task is simply easy, and the "
         "reason is in the data. Rotten fruit in this corpus is dramatically "
         "rotten: brown, collapsed, visibly mouldy. Fresh fruit is unambiguously "
         "fresh. A human annotator can only label confidently at the extremes, "
         "so that is what public corpora contain.")

    para(document,
         "The case a prediction system exists for is the item that is "
         "physiologically past its best and still looks acceptable — the "
         "strawberry that will be inedible tomorrow and photographs fine today. "
         "Those images are systematically absent, because nobody can label them "
         "reliably by eye. A classifier scoring 98% on this corpus has "
         "demonstrated that it can tell obviously fresh from obviously rotten, "
         "which is the case where the user needed no help.")

    rich_para(document, [
        ("RQ2, both halves. ", "b"),
        (f"Transfer-learned MobileNetV2 reaches {R.pct(R.visual['accuracy'])} accuracy distinguishing "
         "fresh from rotten on real photographs. That figure demonstrates "
         "competent visual classification and does not demonstrate early "
         "spoilage detection, because the intermediate state the system is "
         "designed to catch is not represented in the corpus. This is a "
         "limitation of the available public data, not of the model, and it "
         "applies equally to the comparable accuracies in Table 1.", ""),
    ])

    para(document,
         "This is also the strongest argument in the thesis for the sensor "
         "channel. If vision could catch early spoilage, the extra hardware "
         "would be hard to justify. The corpus shows it cannot even be tested on "
         "public data.")

    # ==================================================================
    heading(document, "Three-state classification and the ablation", 2)

    para(document,
         "Four models were trained on identical splits: vision-only, "
         "sensor-only, fusion with raw concatenation, and fusion with the "
         "projected visual embedding.")

    _models = [("Vision only", "vision_only"), ("Sensor only", "sensor_only"),
               ("Fusion, raw concatenation", "fusion_raw"),
               ("Fusion, projected embedding", "fusion")]
    def _cell(model, key):
        value = R.ev[model][key]
        best = max(R.ev[m][key] for _, m in _models)
        return f"**{R.f4(value)}**" if value == best else R.f4(value)
    table(document,
          ["Model", "Accuracy", "Macro F1", "Recall (spoiled)", "Precision (spoiled)"],
          [[label, _cell(m, "accuracy"), _cell(m, "macro_f1"),
            _cell(m, "spoiled_recall"), _cell(m, "spoiled_precision")]
           for label, m in _models],
          "Table 8",
          "Modality ablation on the held-out test split, "
          f"{R.n(sum(R.ev['sensor_only']['per_class'][c]['support'] for c in ('fresh','marginal','spoiled')))} "
          "samples. All "
          "figures depend on simulated sensor features and are bounded by the "
          "discussion below.",
          widths=[5.4, 2.6, 2.6, 3.2, 3.2])

    figure(document, f"{FIG}/ablation.png", "Figure 12",
           "The ablation. Sensor-only leads on accuracy and macro F1, which the "
           "design did not predict.", width_cm=14.5)

    figure(document, f"{FIG}/training_curves.png", "Figure 13",
           "Validation accuracy and loss. Vision-only plateaus early at its "
           "structural ceiling; the fusion variants converge more slowly than "
           "sensor-only and to a lower point.", width_cm=15.5)

    para(document,
         "Per-class figures for the two strongest models show where each spends "
         "its errors.")

    _rows = []
    for label, m in (("Sensor only", "sensor_only"), ("Fusion", "fusion")):
        for i, cls in enumerate(("fresh", "marginal", "spoiled")):
            pc = R.ev[m]["per_class"][cls]
            _rows.append([label if i == 0 else "", cls.capitalize(), R.f4(pc["precision"]),
                          R.f4(pc["recall"]), R.f4(pc["f1"]), str(pc["support"])])
    table(document,
          ["Model", "Class", "Precision", "Recall", "F1", "Support"],
          _rows,
          "Table 10",
          "Per-class metrics for the sensor-only and projected-fusion models on "
          "the test split. Both lose most of their accuracy on the marginal "
          "class, which is the boundary case by construction.",
          widths=[3.6, 2.6, 2.6, 2.4, 2.2, 2.2])

    para(document,
         "Recall on the marginal class is the weak point for both models at "
         f"{R.pct(R.per_class('sensor_only','marginal','recall'))} and "
         f"{R.pct(R.per_class('fusion','marginal','recall'))}, and that is "
         "expected: marginal is defined by two thresholds cut "
         "through a continuous quantity, so items sitting near 0.35 or 0.70 are "
         "genuinely ambiguous rather than misclassified in any meaningful "
         "sense.")

    heading(document, "Vision-only confirms the design as intended", 3)

    para(document,
         f"{R.pct(R.acc('vision_only'))} accuracy is poor, and it is supposed "
         "to be. The corpus pairing gives marginal items images drawn from both "
         "the fresh and rotten pool, so a vision-only model cannot separate "
         "marginal from fresh even in principle. Its confusion matrix shows "
         f"precisely that failure: of {sum(R.cm('vision_only')[1])} marginal "
         f"items it labels {R.cm('vision_only')[1][0]} as fresh and "
         f"{R.cm('vision_only')[1][2]} as spoiled, getting "
         f"{R.cm('vision_only')[1][1]} right. It has effectively learned the "
         "binary task and is guessing at "
         "the middle class.")

    para(document,
         "This confirms the simulation encodes the visual-lag hypothesis it was "
         "designed to encode. It is a check on the experiment, not a finding "
         "about the world.")

    heading(document, "Fusion does not beat its own baseline", 3)

    para(document,
         "The design assumption was that combining modalities would beat either "
         f"alone. It did not. Sensor-only reaches {R.pct(R.acc('sensor_only'))}; "
         f"the best fusion variant reaches {R.pct(R.acc('fusion'))}. Adding the "
         f"visual branch cost {R.fusion_gap_points:.1f} percentage points.")

    para(document,
         "The cause is structural rather than a training accident, and it is "
         "worth spelling out because it constrains what this experiment could "
         "ever have shown. The ground-truth label is derived from spoilage "
         "extent, and spoilage extent is a deterministic function of the same "
         "physical state that generates the sensor features. The sensor branch "
         "therefore has near-direct access to the target. The image is a lagged, "
         "noisy proxy for that state, so once the sensors are present the "
         "visual branch has almost nothing left to contribute and mostly adds "
         "variance.")

    para(document,
         "In other words, the experiment is close to rigged in the sensors' "
         "favour, and not by a choice that could reasonably have been made "
         "differently. Any simulation that generates both the features and the "
         "labels from one physical model will have this property. It is an "
         "argument about what simulated validation of sensor fusion can "
         "establish, and the answer is: less than one would like.")

    para(document,
         "On real hardware the balance would plausibly differ. Real MQ sensors "
         "drift, respond to humidity, cross-react with unrelated compounds, and "
         "measure the whole enclosure's headspace rather than one item. A "
         "camera looking at a specific slot would then carry information the "
         "sensors genuinely lack. But that is a hypothesis about hardware, and "
         "this thesis has no hardware evidence for it.")

    heading(document, "The width of the join matters", 3)

    para(document,
         "The two fusion variants differ only in how the visual embedding enters "
         f"the join, and the difference is {R.projection_gain_points:.1f} "
         f"percentage points of accuracy — {R.pct(R.acc('fusion_raw'))} for raw "
         f"concatenation against {R.pct(R.acc('fusion'))} with the embedding "
         "projected to 64 dimensions first.")

    para(document,
         "Concatenating 1280 visual dimensions with 32 sensor dimensions gives "
         "the image branch forty times the width, and the first fusion layer "
         "allocates capacity in proportion. Where the wide branch carries the "
         "weaker signal, that allocation is exactly backwards. Projecting the "
         "embedding down lets both modalities compete on comparable terms.")

    para(document,
         "This is a small, practical result and the reviewed literature mentions "
         "it rarely. Papers describing late fusion typically report the "
         "architecture and the accuracy without noting that relative branch "
         "width is a hyperparameter with a real effect. On this task, getting it "
         "wrong turned fusion from slightly worse than the sensor baseline into "
         "clearly worse.")

    rich_para(document, [
        ("RQ3 is answered negatively. ", "b"),
        ("Under this simulation, late fusion does not outperform the "
         f"sensor-only baseline: {R.pct(R.acc('fusion'))} against "
         f"{R.pct(R.acc('sensor_only'))}. Branch width at the join "
         "materially affects the result. The negative finding is attributable "
         "to the simulation sharing a generative model between features and "
         "labels, and resolving the question properly requires instrumented "
         "hardware.", ""),
    ])

    heading(document, "Error structure", 3)

    figure(document, f"{FIG}/confusion_sensor_only.png", "Figure 14",
           "Sensor-only confusion matrix. Errors concentrate on the marginal "
           "boundaries, which is where a graded physical quantity has been cut "
           "into discrete classes.", width_cm=10.5)

    para(document,
         "The error pattern is reassuring. "
         + ("No spoiled item is classified as fresh and no fresh item as spoiled; "
            if R.cm('sensor_only')[0][2] == 0 and R.cm('sensor_only')[2][0] == 0
            else f"{R.cm('sensor_only')[2][0]} spoiled items are classified as fresh and "
                 f"{R.cm('sensor_only')[0][2]} fresh as spoiled; otherwise ")
         + "every error is a boundary case "
         "involving the marginal class. That is the expected consequence of "
         "thresholding a continuous quantity, and it is the least costly error "
         "type: mistaking marginal for fresh delays an alert by one cycle, while "
         "the catastrophic error — declaring spoiled food fresh — does not occur "
         "in the test set at all.")

    para(document,
         f"Recall on the spoiled class is {R.pct(R.spoiled_recall('sensor_only'))} for sensor-only, the metric that "
         "matters most because a missed spoiled item is the failure with a "
         "health consequence.")

    figure(document, f"{FIG}/confusion_vision_only.png", "Figure",
           f"Vision-only confusion matrix. Of {sum(R.cm('vision_only')[1])} "
           f"marginal items it assigns {R.cm('vision_only')[1][0]} to fresh and "
           f"{R.cm('vision_only')[1][2]} to spoiled, getting "
           f"{R.cm('vision_only')[1][1]} right — the failure the corpus "
           "construction makes inevitable.", width_cm=10.5)

    figure(document, f"{FIG}/confusion_fusion.png", "Figure",
           "Projected-fusion confusion matrix. The error structure resembles "
           "sensor-only, with slightly more mass on the marginal boundaries.",
           width_cm=10.5)

    para(document,
         "Setting the three matrices side by side makes the ablation concrete. "
         "Vision-only fails on one specific class for a structural reason. "
         "Sensor-only and fusion both concentrate their errors on the same "
         "boundaries; the difference between them is a handful of cases.")

    # ==================================================================
    heading(document, "Inference cost", 2)

    para(document,
         "Cost was profiled per stage rather than end to end, so the expensive "
         "part is identifiable.")

    _st = R.pipe["stages_ms"]
    def _srow(label, key, bold=False):
        w = (lambda x: f"**{x}**") if bold else (lambda x: x)
        return [w(label), w(f"{_st[key]['mean']:.2f}"), w(f"{_st[key]['median']:.2f}"),
                w(f"{_st[key]['p95']:.2f}"), "" if bold else f"{100*_st[key]['share_of_total']:.1f}%"]
    table(document,
          ["Stage", "Mean (ms)", "Median (ms)", "p95 (ms)", "Share"],
          [_srow("JPEG decode and resize", "decode_resize"),
           _srow("Preprocessing", "preprocess"),
           _srow("MobileNetV2 backbone", "backbone"),
           _srow("Fusion head", "fusion_head"),
           _srow("Total per item", "total", bold=True)],
          "Table 9",
          "End-to-end inference cost per item, measured on the development host "
          "(Apple silicon, TensorFlow 2.21), 60 runs after 10 warm-up "
          "iterations.",
          widths=[5.4, 2.6, 2.8, 2.4, 2.2])

    para(document,
         f"The backbone accounts for {R.pct(_st['backbone']['share_of_total'], 0)} of the cost. Everything else together — "
         "decoding, preprocessing and the entire fusion head — is under 4 "
         "milliseconds. Any optimisation effort belongs on the backbone or on "
         "avoiding it, which is one more practical argument for the sensor-only "
         "path: it skips the expensive stage entirely.")

    para(document,
         f"Scaling by a {R.pi_factor:.1f}× single-core slowdown — the ratio of "
         "Geekbench 6 single-core medians for the Apple M1 host and the "
         f"Raspberry Pi 4 (Primate Labs, 2026) — gives roughly {R.pi_ms:.0f} ms "
         f"per item on a Pi 4. Six slots then take about {6*R.pi_ms/1000:.1f} "
         f"seconds of a thirty-minute cycle, a duty cycle of {R.pct(R.duty, 2)}. "
         "Even if that scaling factor is wrong by a factor of three, the "
         "conclusion is unchanged.")

    rich_para(document, [
        ("This is an estimate, not a measurement. ", "b"),
        ("It is derived from a host measurement and a public benchmark ratio, and no "
         "code in this thesis has been timed on Raspberry Pi hardware.", ""),
    ])

    table(document,
          ["Variant", "Size (MB)", "Mean latency (ms)", "Test accuracy"],
          [["Keras, fusion", f"{R.keras_mb('fusion'):.3f}", "—", R.f4(R.acc("fusion"))]]
          + [[f"TFLite {v}", f"{R.tfl('fusion', v, 'megabytes'):.3f}",
              f"{R.tfl('fusion', v, 'mean_ms'):.3f}", R.f4(R.tfl('fusion', v, 'test_accuracy'))]
             for v in ("float32", "float16", "int8")]
          + [["TFLite int8, sensor-only", f"{R.tfl('sensor_only','int8','megabytes'):.3f}",
              f"{R.tfl('sensor_only','int8','mean_ms'):.3f}",
              R.f4(R.tfl('sensor_only','int8','test_accuracy'))]],
          "Table 10",
          "TensorFlow Lite conversion. Latency is for the head alone, excluding "
          "the backbone, which is why the figures are microseconds. Float16 "
          "halves size at no accuracy cost; int8 gives a "
          f"{R.keras_mb('fusion') / R.tfl('fusion','int8','megabytes'):.0f}-fold reduction "
          f"for {100*(R.acc('fusion') - R.tfl('fusion','int8','test_accuracy')):.1f} points of accuracy.",
          widths=[5.4, 2.8, 3.4, 3.0])

    para(document,
         "Float16 is the sensible default: half the size, no measurable accuracy "
         "cost. Int8 is worth it only where storage is genuinely tight, which on "
         "a device with a 64 GB card it is not.")

    rich_para(document, [
        ("RQ4 is answered affirmatively, with a caveat. ", "b"),
        (f"Estimated inference cost uses about {R.pct(R.duty, 1)} of the measurement cycle on "
         "a Raspberry Pi 4, leaving very large headroom. The estimate has not "
         "been confirmed on hardware.", ""),
    ])

    # ==================================================================
    heading(document, "System behaviour", 2)

    para(document,
         "The complete system was exercised by running the real acquisition and "
         "inference path against the simulated backend with time compressed: "
         f"six slots, {R.demo['hours_per_cycle']:.0f} simulated hours per cycle, "
         f"{R.demo['cycles']} cycles.")

    table(document,
          ["Simulated day"] + [s["commodity"].capitalize() for s in R.demo["shelf"]],
          R.demo_rows(),
          "Table 11",
          f"State and freshness score across an accelerated {R.demo_days:.0f}-day "
          "run, read from the run's log. The commodities fail in the order "
          "their published shelf lives predict.",
          widths=[2.6, 2.6, 2.4, 2.4, 2.4, 2.4, 2.6], font_size=8.0)

    para(document,
         "The ordering is the useful observation. Nothing in the runtime code "
         "knows about shelf lives; the model produces sensor readings, the "
         "classifier reads them, and the ordering emerges. It confirms that the "
         "pipeline is wired correctly from physics through inference to the "
         "interface.")

    para(document,
         "It is a test of the plumbing, not evidence about food. The commodities "
         "fail in the right order because the physical model says they should, "
         "and the physical model was calibrated to say so.")

    para(document,
         "Alert behaviour worked as designed. Across the run the system raised "
         "alerts only at transitions into a new state, and "
         "stayed silent while items remained in a state they had already "
         "reported. Without transition-triggered alerting the same run would "
         "have produced dozens of notifications about the same strawberry.")

    figure(document, f"{FIG}/ui_stats.png", "Figure 15",
           "The waste-tracking view. These counters are what a longitudinal "
           "study would read out; here they are empty because no real "
           "consumption has been recorded.", width_cm=12.0)

    # ==================================================================
    heading(document, "Discussion", 2)

    heading(document, "What the work establishes", 3)

    para(document,
         "Four things stand independently of the simulation caveat.")

    reset_numbering()
    numbered(document,
             "A physical spoilage model built from published predictive "
             "microbiology reproduces literature shelf lives to within 1.7% "
             "across eight commodities and extrapolates correctly in "
             "temperature. It is reusable independently of the rest of the "
             "system.")
    numbered(document,
             "Transfer-learned MobileNetV2 classifies fresh from rotten "
             f"produce at {R.pct(R.visual['accuracy'])} on a leakage-controlled "
             "split of real photographs.")
    numbered(document,
             "Public fresh-versus-rotten corpora contain the easy cases and "
             "omit the intermediate state that matters, so accuracies measured "
             "on them, including the one above, overstate what a deployed "
             "system would achieve.")
    numbered(document,
             "Near-duplicate leakage can be invisible to hash-based duplicate "
             f"detection while affecting {R.pct(R.naive_leak, 0)} of a test set, and an "
             "embedding-space audit finds it cheaply.")

    heading(document, "What it does not establish", 3)

    para(document,
         "The three-state results depend entirely on simulated sensor features "
         "whose generative model also produced the labels. They demonstrate that "
         "the architecture trains, converges and can exploit sensor information "
         "under a stated model. They are not evidence about a refrigerator.")

    para(document,
         "No claim is made about waste reduction. Published trials of food "
         "tracking applications report reductions on the order of twenty percent "
         "over several weeks, but those are different interventions studied by "
         "other people, and quoting them as though they were an outcome of this "
         "work would be dishonest.")

    para(document,
         "No usability evaluation was run. The interface follows Nielsen's "
         "heuristics and the reasoning is documented, but documented reasoning "
         "is a hypothesis about users.")

    heading(document, "On the negative result", 3)

    para(document,
         "The finding that fusion does not beat the sensor baseline is the one "
         "most tempting to bury, and it is probably the most useful thing in the "
         "thesis.")

    para(document,
         f"Reporting only the fusion accuracy would have been easy. {R.pct(R.acc('fusion'))} on a "
         "three-class problem reads well, sits comfortably beside the "
         "literature in Table 1, and nobody would have asked what the baselines "
         "were — because, as Chapter 3 notes, most published work does not "
         "report them either. The comparison exists only because objective 4 "
         "committed to making it before the answer was known.")

    para(document,
         "The result carries a methodological point beyond this system. When "
         "sensor data is simulated from the same model that generates the "
         "labels, the sensor branch has privileged access to the target, and any "
         "fusion experiment built that way is biased towards the sensors before "
         "training starts. Simulated validation can show that an architecture "
         "trains and can be profiled. It cannot settle whether fusion helps. "
         "Published fusion results validated on synthetic sensor data should be "
         "read with that in mind, including these.")

    heading(document, "What a hardware validation would have to show", 3)

    para(document,
         "Since the central negative result is attributed to the simulation, it "
         "is only fair to specify what evidence would overturn it. Three things "
         "would have to be measured on a real shelf.")

    para(document,
         "First, that gas concentration genuinely leads visible change, and by "
         "how much. The electronic-nose literature supports the direction, but "
         "the visual-lag thresholds used here were chosen rather than measured, "
         "and they determine the difficulty of the whole three-state task. "
         "Photographing items on a fixed schedule while logging gas readings, "
         "with independent spoilage judgements, would give the real lag per "
         "commodity.")

    para(document,
         "Second, that real sensor noise is worse than modelled in a way that "
         "leaves room for vision to help. The simulation includes quantisation, "
         "Gaussian noise and heater drift, but not cross-sensitivity to "
         "unrelated compounds, not the mixing problem when several foods share "
         "one headspace, and not sensor-to-sensor variation. Each of those "
         "degrades the sensor channel specifically, which is where the headroom "
         "for fusion would come from.")

    para(document,
         "Third, that a camera aimed at one slot carries information the shared "
         "headspace cannot. This is the strongest theoretical argument for "
         "fusion and the simulation cannot test it at all, because the modelled "
         "gas reading is already per-item. On real hardware, gas is a property "
         "of the enclosure while an image is a property of a slot, and that "
         "asymmetry is exactly the kind of complementarity late fusion exists "
         "to exploit.")

    para(document,
         "If all three held, fusion would plausibly beat the sensor baseline on "
         "real data despite losing to it here. That is a testable prediction "
         "rather than a defence of the result, and it is the first thing the "
         "hardware work in Chapter 6 should check.")

    heading(document, "On engineering defects and where they hid", 3)

    para(document,
         "Five bugs in this work produced plausible output while being wrong, "
         "and the pattern is worth recording.")

    para(document,
         "The log-basis error made every shelf life 2.3× too short. The curves "
         "were the right shape and only comparison against published values "
         "exposed it. The MQ direction error silently zeroed the ethanol channel "
         "above the low tens of ppm; the readings looked like a quiet sensor "
         "rather than a broken conversion. Double preprocessing trained the "
         f"visual model to exactly chance while stage one had reached {R.pct(R.stage1_final_val)}, and "
         "the loss curve was smooth throughout. Registering a 250 g punnet "
         "against an 18 g simulated berry produced a mass delta far outside the "
         "training distribution, and every item read as spoiled — a result that "
         "looked like a working spoilage detector being pessimistic. And "
         "per-item randomness seeded from Python's hash() of a string — which "
         "the interpreter salts differently in every process — meant the "
         "sensor corpus changed on every run while the documentation promised "
         "exact reproducibility; the numbers were always plausible, just never "
         "the same twice.")

    para(document,
         "None was caught by inspection. Each was caught by comparing against "
         "something external: published shelf lives, a round-trip identity, a "
         "previous stage's score, a physical plausibility bound. Every one now "
         "has a regression test, and those tests are more valuable than the "
         "fixes, because the same class of mistake will be made again.")

    heading(document, "Threats to validity", 3)

    para(document,
         "Setting the limitations out systematically is more useful than a "
         "paragraph of caveats, so they are grouped by the kind of validity each "
         "threatens.")

    rich_para(document, [
        ("Construct validity. ", "b"),
        ("The three states are cuts through a continuous physical quantity at "
         "0.35 and 0.70, and those boundaries were chosen by convention rather "
         "than derived from a sensory panel or a microbiological rejection "
         "threshold. A different pair of cuts would produce different accuracy "
         "figures on identical data. Whether a modelled extent of 0.70 "
         "corresponds to what a person would call spoiled is untested.", ""),
    ])

    rich_para(document, [
        ("Internal validity. ", "b"),
        ("The strongest threat is the one already discussed: sensor features "
         "and labels share a generative model, which biases the ablation toward "
         "the sensor branch before training starts. A secondary threat is that "
         "the visual-lag thresholds directly determine how hard the three-state "
         "task is, and they were chosen rather than measured. Set them equal to "
         "the marginal boundary and vision-only performance would rise "
         "substantially; set them higher and it would fall further.", ""),
    ])

    rich_para(document, [
        ("External validity. ", "b"),
        ("Eight commodities, all fruit, photographed under conditions unlike a "
         "refrigerator interior. No dairy, meat or cooked food, which is where "
         "the health stakes concentrate. The simulated fridge population spans "
         "2.5 to 7.5 °C and 6 to 24 door openings a day, which is a guess at "
         "domestic variation rather than a measured distribution.", ""),
    ])

    rich_para(document, [
        ("Conclusion validity. ", "b"),
        ("Every model was trained once with a fixed seed rather than across "
         "multiple runs, so no confidence intervals are reported and differences "
         "of a few tenths of a point should not be over-read. The 0.9-point gap "
         "between sensor-only and fusion is larger than typical seed variation "
         "for models of this size, but that assertion is not backed by repeated "
         "runs and should be treated as an impression rather than a "
         "result.", ""),
    ])

    heading(document, "Sensitivity to the class boundaries", 3)

    para(document,
         "Because the boundaries are conventions, it is fair to ask how much the "
         "headline numbers depend on them. The error structure gives a partial "
         "answer without needing a separate experiment. All errors in the "
         "sensor-only model involve the marginal class and none crosses from "
         "fresh to spoiled, which means the model is ordering items correctly "
         "and disagreeing only about where the cuts fall.")

    para(document,
         "Collapsing to a binary safe-or-not decision at the 0.70 boundary would "
         f"therefore give a considerably higher accuracy than {R.pct(R.acc('sensor_only'))}, because "
         "every fresh-marginal confusion disappears. That number is not reported "
         "as a result, because choosing the threshold after seeing the errors is "
         "how accuracy figures get inflated, and this thesis has already spent a "
         "section on why such figures should be distrusted.")

    heading(document, "Comparison with related work", 3)

    para(document,
         "Set against Table 1, the accuracies here are comparable to published "
         "figures. That comparison is close to meaningless and is included "
         "because a reader will make it anyway. Each study measured a different "
         "class definition on a different private corpus of unknown difficulty. "
         "A 92% on a hard three-class problem with genuinely ambiguous cases "
         f"beats a {R.pct(R.visual['accuracy'], 0)} on a corpus of obviously-rotten fruit, and nothing in the "
         "published metadata lets anyone tell which is which.")

    para(document,
         "Where this work differs is in what it publishes: the complete "
         "implementation, the dataset audit, the ablation baselines, and the "
         "results that did not support the design. That is the more useful "
         "contribution, and it is available for someone else to check.")
